# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master*
    - develop*
    - feature*
    - release*
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build src/WhatsYourFace.sln --configuration $(buildConfiguration)
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishBuildArtifacts@1

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: AzureRmWebAppDeployment@3
  condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  inputs:
    azureSubscription: 'Azure VSSub WYF Test1'
    WebAppName: 'WhatsYourFaceFrontend-Test1'
    Package: $(System.ArtifactsDirectory)/**/*.zip